roboto-fontface.css: ../../../node_modules/roboto-fontface/css/roboto/roboto-fontface.css
	sed 's/\.\.\/\.\.\/fonts\//..\/fonts\//g' ../../../node_modules/roboto-fontface/css/roboto/roboto-fontface.css > roboto-fontface.css

